Repository ansible/ansible-language-server, pull requests merged in 2021-09, with the labels that each got.

#12 Improve how Git treats changelog and locks in diffs
  .gitattributes
Labels: enhancement, new

#10 Move the package under the `@ansible` scope
  package.json
Labels: enhancement, help wanted, new

#19 Fix path to the YAML fixtures in tests
  test/utils/yaml.test.ts
Labels: bug, new

#22 chore: remove yarn
  .gitattributes
  README.md
  package.json
  yarn.lock
Labels: skip-changelog

#24 doc: mention users of this project
  README.md
Labels: documentation

#23 chore: enforce npm and node requirements
  .npmrc
  package.json
Labels: skip-changelog

#25 fix: correct package-lock.json
  package-lock.json
Labels: bug

#18 Add initial GHA setup
  .github/workflows/ci.yml
Labels: new

#33 chore: add minimal linting
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  jinja-language-configuration.json
  package.json
  test/data/utils/yaml/ancestryBuilder.yml
Labels: skip-changelog

#34 Add lint checks for exec bit and json validity
  .pre-commit-config.yaml
  scripts/tsconfig.json
Labels: skip-changelog

#35 Add check for syntaxes files
  .github/workflows/ci.yml
  package.json
  scripts/build-syntaxes
  test-requirements.txt
Labels: skip-changelog

#36 Add eslint execution to linting
  .pre-commit-config.yaml
  scripts/.eslintrc.js
  scripts/check-dependencies.js
Labels: skip-changelog

#41 Fix pre-commit.ci job
  .pre-commit-config.yaml
Labels: skip-changelog

#46 chore: avoid changing quotes on yaml files
  .prettierrc
  .prettierrc.yaml
Labels: skip-changelog

#38 Check that module paths are directories before globbing them
  src/utils/docsFinder.ts
Labels: bug

#47 fix: bump ansi-regex dependency to 5.0.1
  package-lock.json
Labels: bug

#45 Rewrite the `build-syntaxes` script in pure Python
  .pre-commit-config.yaml
  package.json
  scripts/build-syntaxes
  test-requirements.txt
Labels: skip-changelog
