Repository ansible/ansible-language-server, pull requests merged in 2021-11, with the labels that each got.

#103 Reword the change note for v0.2.6
  CHANGELOG.md
Labels: documentation, skip-changelog

#105 Release 0.2.6 from GitHub Actions CI/CD
  package-lock.json
  package.json
Labels: skip-changelog

#110 Fix issue with container copy command
  src/services/executionEnvironment.ts
Labels: bug

#109 Update plugin doc cache validate logic for execution environment
  src/services/executionEnvironment.ts
Labels: bug

#111 Update container cleanup logic for execution environment
  src/services/executionEnvironment.ts
Labels: enhancement

#114 Switch the default execution environment image to `ansible/ansible-devtools-demo-ee`
  src/services/settingsManager.ts
Labels: enhancement

#119 Auto-mark the issues as `new` on creation
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: new, skip-changelog

#118 Auto-cancel stale workflows per-PR
  .github/workflows/ci.yml
Labels: enhancement, new, skip-changelog

#116 Add support for nested module options (suboptions)
  README.md
  src/interfaces/module.ts
  src/providers/completionProvider.ts
  src/providers/hoverProvider.ts
  src/providers/semanticTokenProvider.ts
  src/utils/docsParser.ts
  src/utils/yaml.ts
Labels: enhancement

#129 Repair vscode pipeline
  .github/workflows/vscode.yml
Labels: skip-changelog

#130 Ensure npm link uses --save
  .github/workflows/vscode.yml
Labels: skip-changelog

#125 Fix the tests under the Windows runtime
  test/utils/yaml.test.ts
Labels: bug, skip-changelog, gate

#132 Adopt use of creator-ee
  src/services/settingsManager.ts
Labels: bug

#120 Prepare 0.3.0 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#134 Avoid git am failure with empty patches
  .github/workflows/ci.yml
Labels: skip-changelog

#136 Partially revert "Prepare 0.3.0 release"
  package-lock.json
  package.json
Labels: skip-changelog

#137 Only allow bumping the version from CI/CD
  bin/version-bump-allowed
  package.json
Labels: skip-changelog

#141 Release 0.3.0 from GitHub Actions CI/CD
  package-lock.json
  package.json
Labels: skip-changelog

#140 Allow use of Ansible files without a workspace
  src/services/workspaceManager.ts
Labels: bug

#142 Avoid exception with undefined linter arguments settings
  src/services/ansibleLint.ts
Labels: bug

#144 Add code coverage reporting
  .github/workflows/ci.yml
  .gitignore
  codecov.yml
  package-lock.json
  package.json
Labels: skip-changelog

#146 Create a release PR on successful publishing
  .github/workflows/ci.yml
Labels: skip-changelog

#147 Fix downstream `vscode` workflow to use `test:ui`
  .github/workflows/vscode.yml
Labels: skip-changelog

#158 Implement changelog management with Towncrier
  .github/chronographer.yml
  .gitignore
  .pre-commit-config.yaml
  CHANGELOG.md
  docs/changelog-fragments.d/.CHANGELOG-TEMPLATE.md.j2
  docs/changelog-fragments.d/.gitignore
  docs/changelog-fragments.d/158.misc.md
  docs/changelog-fragments.d/README.md
  pyproject.toml
  tox.ini
Labels: documentation, enhancement, skip-changelog
