Repository ansible/ansible-language-server, pull requests merged in 2022-08, with the labels that each got.

#413 Expose metadata about environment to the client
  src/ansibleLanguageService.ts
  src/services/ansibleConfig.ts
  src/services/executionEnvironment.ts
  src/services/workspaceManager.ts
  src/utils/getAnsibleMetaData.ts
  test/fixtures/utils/getAnsibleMetaData/ansible.cfg
  test/fixtures/utils/getAnsibleMetaData/inventory
  test/fixtures/utils/getAnsibleMetaData/plays.yml
  test/helper.ts
  test/utils/getAnsibleMetaData.test.ts
Labels: enhancement

#420 Disable python debugger when running external commands
  .config/dictionary.txt
  src/utils/misc.ts
Labels: bug

#425 Enable caching of podman image on macos
  .github/workflows/task.yml
Labels: skip-changelog

#426 Bump dependencies
  .config/requirements.txt
  .pre-commit-config.yaml
  package-lock.json
  package.json
Labels: skip-changelog
