Repository ansible/ansible-language-server, pull requests merged in 2022-04, with the labels that each got.

#286 Add neovim to dictionary
  .config/dictionary.txt
Labels: bot:chronographer:skip

#285 fix: add insertTextFormat to completionItem
  docs/changelog-fragments.d/285.bugfix.md
  src/providers/completionProvider.ts
Labels: bug, bot:chronographer:provided

#288 Autocomplete option and suboption choices
  docs/changelog-fragments.d/288.feature.md
  src/providers/completionProvider.ts
  test/fixtures/common/collections/ansible_collections/org_1/coll_4/plugins/modules/module_1.py
  test/fixtures/completion/simple_tasks.yml
  test/providers/completionProvider.test.ts
Labels: enhancement, bot:chronographer:provided

#294 Utility to update settings in readme automatically
  .config/dictionary.txt
  .pre-commit-config.yaml
  .prettierignore
  README.md
  docs/changelog-fragments.d/294.feature.md
  docs/index.md
  docs/settings.md
  package-lock.json
  package.json
  src/interfaces/extensionSettings.ts
  src/services/settingsManager.ts
  tools/settings-doc-generator.ts
Labels: documentation, enhancement, skip-changelog, bot:chronographer:provided

#296 Ensure we keep generated settings docs in sync
  .github/workflows/ci.yml
  .gitignore
  README.md
  tox.ini
Labels: bot:chronographer:skip

#295 Replace globby with glob
  docs/changelog-fragments.d/295.bugfix.md
  package-lock.json
  package.json
  src/utils/docsFinder.ts
  test/fixtures/utils/docsFinder/1.py
  test/fixtures/utils/docsFinder/10.json
  test/fixtures/utils/docsFinder/2.py
  test/fixtures/utils/docsFinder/3.py
  test/fixtures/utils/docsFinder/4.yml
  test/fixtures/utils/docsFinder/5.yml
  test/fixtures/utils/docsFinder/6.yaml
  test/fixtures/utils/docsFinder/_7.py
  test/fixtures/utils/docsFinder/_8.py
  test/fixtures/utils/docsFinder/_9.py
  test/utils/docsFinder.test.ts
Labels: bug, bot:chronographer:provided

#299 Move glob utils to different utils file
  docs/changelog-fragments.d/299.misc.md
  src/utils/docsFinder.ts
  src/utils/pathUtils.ts
  test/utils/pathUtils.test.ts
Labels: bug, bot:chronographer:provided

#289 Add vscode extension e2e test in CI
  .github/workflows/vscode.yml
Labels: bot:chronographer:skip

#298 Refactor use of python dependencies
  .config/dictionary.txt
  .readthedocs.yml
  docs/requirements.in
  docs/requirements.txt
  requirements.in
  requirements.txt
  setup.cfg
  tox.ini
Labels: bot:chronographer:skip

#301 Add utility to sync als version for devel CI job
  .github/workflows/vscode.yml
  tools/version_sync.py
Labels: bot:chronographer:skip

#302 Remove release cleanup pipeline
  .github/workflows/ci.yml
Labels: bot:chronographer:skip

#303 Fix execution of tox -e deps
  requirements.txt
  tox.ini
Labels: bot:chronographer:skip

#305 Move handlebars to dev dependencies
  package-lock.json
  package.json
Labels: bot:chronographer:skip

#308 Bump npm dependencies
  package-lock.json
  package.json
  tox.ini
Labels: bot:chronographer:skip
