Repository ansible/ansible-language-server, pull requests merged in 2022-06, with the labels that each got.

#345 Add check to validate mount path before passing it as an arg in EE
  docs/changelog-fragments.d/345.bugfix.md
  src/services/executionEnvironment.ts
Labels: bug, bot:chronographer:provided

#351 Update test dependencies
  docs/_ext/spelling_stub_ext.py
  docs/changelog.md
  docs/conf.py
  docs/contributing/guidelines.md
  docs/contributing/security.md
  docs/index.md
  requirements.txt
  setup.cfg
  tox.ini
Labels: skip-changelog, bot:chronographer:skip

#349 Replace tox with taskfile as build tool
  .config/dictionary.txt
  .github/workflows/release.yml
  .github/workflows/task.yml
  .gitignore
  .pre-commit-config.yaml
  Taskfile.yml
  docs/conf.py
  docs/contributing/guidelines.md
  package.json
  requirements.txt
  setup.cfg
  tools/docs_summary.py
  tools/test-setup.sh
  tox.ini
Labels: skip-changelog, bot:chronographer:skip

#352 Update dependencies
  .pre-commit-config.yaml
  package-lock.json
  package.json
Labels: skip-changelog, bot:chronographer:skip

#348 Add settings for completion
  docs/changelog-fragments.d/348.feature.md
  docs/settings.md
  src/interfaces/extensionSettings.ts
  src/providers/completionProvider.ts
  src/services/settingsManager.ts
Labels: enhancement, bot:chronographer:provided

#356 Refactor npm package
  .npmignore
  package.json
Labels: bug

#354 Remove syntaxes from ALS
  .pre-commit-config.yaml
  .prettierignore
  Taskfile.yml
  cspell.config.yaml
  scripts/build-syntaxes
  syntaxes/README.md
  syntaxes/ansible/generated/jinja-braces.tmLanguage
  syntaxes/ansible/generated/jinja-conditionals.tmLanguage
  syntaxes/ansible/generated/jinja-double-quote-escape.tmLanguage
  syntaxes/ansible/generated/jinja-extras.tmLanguage
  syntaxes/ansible/generated/jinja-single-quote-escape.tmLanguage
  syntaxes/ansible/generated/keywords.tmLanguage
  syntaxes/ansible/jinja-braces.tmLanguage.plist
  syntaxes/ansible/jinja-conditionals.tmLanguage.plist
  syntaxes/ansible/jinja-double-quote-escape.tmLanguage.plist
  syntaxes/ansible/jinja-extras.tmLanguage.plist
  syntaxes/ansible/jinja-single-quote-escape.tmLanguage.plist
  syntaxes/ansible/keywords.tmLanguage.plist
  syntaxes/external/YAML.tmLanguage
  syntaxes/external/YAML.tmLanguage.plist
  syntaxes/external/jinja.tmLanguage.json
  syntaxes/plist2xml.py
  syntaxes/xml2plist.py
Labels: skip-changelog, bot:chronographer:skip

#358 Remove language configurations files
  .pre-commit-config.yaml
  .prettierignore
  ansible-language-configuration.json
  jinja-language-configuration.json
Labels: skip-changelog, bot:chronographer:skip

#361 Remove old version-bump-allowed script
  bin/version-bump-allowed
  package.json
Labels: skip-changelog, bot:chronographer:skip

#362 Move py related configs under .config
  .config/requirements.in
  .config/requirements.txt
  .github/CONTRIBUTING.md
  .github/dependabot.yml
  .github/workflows/vscode.yml
  .readthedocs.yml
  Taskfile.yml
  cspell.config.yaml
  docs/changelog-fragments.d/.CHANGELOG-TEMPLATE.md.j2
  docs/changelog-fragments.d/.gitignore
  docs/changelog-fragments.d/329.bugfix.md
  docs/changelog-fragments.d/331.misc.md
  docs/changelog-fragments.d/345.bugfix.md
  docs/changelog-fragments.d/348.feature.md
  docs/changelog-fragments.d/README.md
  docs/changelog.md
  docs/conf.py
  docs/contributing/guidelines.md
  pyproject.toml
  setup.cfg
  tools/docs_summary.py
  tools/test-setup.sh
Labels: skip-changelog, bot:chronographer:skip

#363 Fix documentation version reading
  .config/mypy.ini
  .vscode/settings.json
  docs/conf.py
Labels: bug

#364 Temporary remove vscode pipeline
  .github/workflows/vscode.yml
Labels: skip-changelog

#366 Enable caching on GHA
  .github/workflows/task.yml
Labels: skip-changelog

#370 Add release pipeline for generating changelog
  .github/workflows/release.yml
  .gitignore
  CHANGELOG.md
  Taskfile.yml
  cspell.config.yaml
  tools/mk_changelog.sh
Labels: skip-changelog

#373 Update release task
  Taskfile.yml
  tools/mk_changelog.sh
  tools/test-setup.sh
Labels: skip-changelog

#374 More release work
  .config/dictionary.txt
  tools/mk_changelog.sh
  tools/test-setup.sh
Labels: skip-changelog

#375 More release work
  .github/workflows/release.yml
  Taskfile.yml
  tools/release.sh
Labels: skip-changelog

#379 Release v0.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#380 More release work
  .config/dictionary.txt
  .github/workflows/publish.yml
  .github/workflows/release.yml
  Taskfile.yml
  tools/release.sh
  tools/test-setup.sh
Labels: skip-changelog

#383 More taskfile
  .config/dictionary.txt
  .config/requirements.in
  .config/requirements.txt
  .envrc
  .github/workflows/task.yml
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  Taskfile.yml
  out/.gitignore
  tools/release.sh
  tools/test-setup.sh
Labels: skip-changelog

#384 Update dependencies
  package-lock.json
  package.json
Labels: skip-changelog

#385 Bump deps
  package-lock.json
  package.json
Labels: skip-changelog
