Repository ansible/ansible-language-server, pull requests merged in 2022-10, with the labels that each got.

#448 Update settings to disable validation
  docs/settings.md
  src/interfaces/extensionSettings.ts
  src/providers/validationProvider.ts
  src/services/ansibleLint.ts
  src/services/settingsManager.ts
  src/utils/execPath.ts
  test/providers/completionProvider.test.ts
  test/providers/settingsManager.test.ts
  test/providers/validationProvider.test.ts
Labels: enhancement

#453 Minor build script fixes
  .pre-commit-config.yaml
  Taskfile.yml
  tools/test-setup.sh
Labels: skip-changelog

#454 Update ansible and ansible-lint
  .config/requirements.in
  .config/requirements.txt
  tools/test-setup.sh
Labels: skip-changelog

#451 Fix bug related to diagnostics caching when validation is disabled
  src/providers/validationProvider.ts
  test/providers/validationProvider.test.ts
Labels: bug

#459 Start testing with ansible-core 2.14 pre-releases
  .config/requirements.in
  .config/requirements.txt
  .github/workflows/task.yml
  tools/test-setup.sh
Labels: skip-changelog

#462 Add default tmp location for ansible
  src/services/executionEnvironment.ts
Labels: bug

#449 Support for FQCN with more than 3 elements
  src/services/docsLibrary.ts
  src/utils/docsFinder.ts
  test/fixtures/common/collections/ansible_collections/org_1/coll_5/galaxy.yml
  test/fixtures/common/collections/ansible_collections/org_1/coll_5/plugins/modules/sub_coll_1/module_1.py
  test/fixtures/completion/simple_tasks.yml
  test/providers/completionProvider.test.ts
Labels: bug

#461 Add documentation link for violated ansible-lint rules
  src/services/ansibleLint.ts
  test/providers/validationProvider.test.ts
Labels: bug

#474 Add support for ansible-lint config file
  src/services/ansibleLint.ts
  src/utils/getAnsibleMetaData.ts
  test/fixtures/diagnostics/.ansible-lint
  test/fixtures/diagnostics/lint_errors.yml
  test/providers/validationProvider.test.ts
  test/utils/getAnsibleMetaData.test.ts
Labels: bug

#475 Enhance ansible meta-data
  .prettierrc.yaml
  src/utils/getAnsibleMetaData.ts
  test/utils/getAnsibleMetaData.test.ts
Labels: bug
