Repository ansible/ansible-language-server, pull requests merged in 2022-11, with the labels that each got.

#479 Bump ansible-lint version from 6.8.4 to 6.8.6
  .config/requirements.txt
Labels: skip-changelog

#480 Update code to use latest tag of creator-ee
  Taskfile.yml
  src/services/settingsManager.ts
  tools/test-setup.sh
Labels: skip-changelog

#478 Avoid parsing ansible-lint config file
  src/interfaces/ansibleLintConfig.ts
  src/services/ansibleLint.ts
  src/services/workspaceManager.ts
Labels: bug

#488 Update pre-commit
  .pre-commit-config.yaml
  package-lock.json
  package.json
Labels: skip-changelog

#489 Use ghcr.io instead of quay.io as default registry
  Taskfile.yml
  docs/settings.md
  src/services/settingsManager.ts
  test/utils/getAnsibleMetaData.test.ts
  tools/test-setup.sh
Labels: skip-changelog

#493 Fix broken pipe caused by head -n
  tools/test-setup.sh
Labels: bug, skip-changelog

#494 Update docs url
  README.md
Labels: bug

#492 Isolate container caching from others
  .github/workflows/task.yml
Labels: bug

#498 Resume podman machine
  .github/workflows/task.yml
  tools/test-setup.sh
Labels: skip-changelog

#499 GHA use ubuntu 22.04
  .github/workflows/task.yml
  .readthedocs.yml
Labels: skip-changelog

#500 Update dependencies
  .pre-commit-config.yaml
  package-lock.json
  package.json
Labels: skip-changelog

#501 Improve testing output
  .mocharc.yml
  test/rootMochaHooks.ts
Labels: skip-changelog

#505 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#504 Reduce container name length
  .config/dictionary.txt
  package-lock.json
  package.json
  src/services/executionEnvironment.ts
Labels: skip-changelog

#507 Remove als acronym from docs website title
  docs/conf.py
Labels: bug

#509 Add note about task vs go-task
  .github/CONTRIBUTING.md
Labels: bug
