Repository ansible/ansible-language-server, pull requests merged in 2022-01, with the labels that each got.

#175 chore: fix broken spellcheck-docs
  docs/requirements.in
  docs/requirements.txt
  tox.ini
Labels: skip-changelog, bot:chronographer:skip

#174 chore: avoid coverage report on failed test runs
  package.json
Labels: skip-changelog, bot:chronographer:skip

#176 chore: fix nyc includes
  .nycrc.yml
Labels: skip-changelog, bot:chronographer:skip

#178 chore: prepare md for prettier
  .github/CONTRIBUTING.md
  CHANGELOG.md
  README.md
  docs/changelog-fragments.d/README.md
  docs/changelog.md
  docs/index.md
Labels: skip-changelog, bot:chronographer:skip

#180 chore: improve mocha configuration
  .mocharc.yml
  .vscode/extensions.json
  .vscode/settings.json
  package.json
Labels: skip-changelog, bot:chronographer:skip

#179 Autoformat json files using prettier
  .pre-commit-config.yaml
  .prettierrc.yaml
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  scripts/tsconfig.esm.json
  scripts/tsconfig.json
  scripts/tsconfig.umd.json
  tsconfig.json
Labels: skip-changelog, bot:chronographer:skip

#182 tests: make doc loading reusable
  test/data/yaml/ancestryBuilder.yml
  test/data/yaml/getDeclaredCollections.yml
  test/data/yaml/isBlockParam.yml
  test/data/yaml/isPlayParam.yml
  test/data/yaml/isRoleParam.yml
  test/data/yaml/isTaskParam.yml
  test/data/yaml/test.json
  test/utils/helper.ts
  test/utils/yaml.test.ts
Labels: skip-changelog, bot:chronographer:skip

#181 Make markdown refs compatible with prettier
  .github/CODE_OF_CONDUCT.md
  docs/changelog-fragments.d/158.misc.md
  docs/changelog-fragments.d/161.misc.md
  docs/changelog-fragments.d/164.doc.md
  docs/changelog-fragments.d/README.md
  docs/contributing/guidelines.md
Labels: skip-changelog, bot:chronographer:skip

#185 Move isWindows to helpers
  test/utils/helper.ts
  test/utils/yaml.test.ts
Labels: skip-changelog, bot:chronographer:skip

#184 Add tests for commandRunner
  .github/workflows/ci.yml
  test/utils/runCommand.test.ts
Labels: skip-changelog, bot:chronographer:skip

#186 Fix nyc configuration
  .nycrc.yml
  package.json
Labels: skip-changelog, bot:chronographer:skip

#187 chore: fix codecov.yml
  .pre-commit-config.yaml
  codecov.yml
Labels: skip-changelog, bot:chronographer:skip

#189 Add defaults to settings section of README.md
  README.md
Labels: documentation, skip-changelog, bot:chronographer:skip

#193 Make Windows tests unblock the CI/PR gating mechanism
  .github/workflows/ci.yml
Labels: enhancement, new, portability, bot:chronographer:skip

#196 Reformat typescript using prettier
  .pre-commit-config.yaml
  src/services/ansibleConfig.ts
  src/services/executionEnvironment.ts
  src/services/settingsManager.ts
  src/services/workspaceManager.ts
  src/utils/misc.ts
  test/utils/helper.ts
  test/utils/runCommand.test.ts
  test/utils/yaml.test.ts
Labels: skip-changelog, bot:chronographer:skip
