Repository ansible/ansible-language-server, pull requests merged in 2022-03, with the labels that each got.

#195 Emit notification about unsupported platforms
  docs/changelog-fragments.d/195.feature.md
  src/server.ts
  src/utils/misc.ts
Labels: enhancement, bot:chronographer:provided

#236 Ensure ansible output is parseable
  docs/changelog-fragments.d/236.bugfix.md
  src/utils/misc.ts
  test/utils/runCommand.test.ts
Labels: bug, bot:chronographer:provided

#190 Use `ls` instead of `find` for EE ansible docs
  docs/changelog-fragments.d/190.bugfix.md
  src/services/executionEnvironment.ts
Labels: bug, bot:chronographer:provided

#239 Bump test dependencies
  package-lock.json
  package.json
Labels: bot:chronographer:skip

#233 Remove usage of URL from `fileExists()`
  docs/changelog-fragments.d/233.bugfix.md
  src/services/metadataLibrary.ts
  src/utils/misc.ts
Labels: bug, bot:chronographer:provided

#212 Enable wsl1 testing using npm pipeline
  .github/workflows/npm.yml
  tools/test-setup.sh
Labels: skip-changelog, bot:chronographer:skip

#244 Enable cspell
  .config/dictionary.txt
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  cspell.config.yaml
  docs/conf.py
  docs/contributing/guidelines.md
  src/utils/ansible.ts
  src/utils/docsParser.ts
  src/utils/yaml.ts
  test/utils/yaml.test.ts
  tools/test-setup.sh
  tox.ini
Labels: skip-changelog, bot:chronographer:skip

#248 Use a single spellchecking dictionary
  .config/dictionary.txt
  docs/conf.py
  docs/spelling_wordlist.txt
Labels: bot:chronographer:skip

#249 Fix docs requirements
  docs/requirements.in
Labels: bug, bot:chronographer:skip

#250 Fix minor docs build issues
  .gitignore
  tox.ini
Labels: bug, bot:chronographer:skip

#243 Enhance fallback to --syntax-check logic
  .config/dictionary.txt
  docs/changelog-fragments.d/243.feature.md
  src/services/ansibleLint.ts
Labels: enhancement, bot:chronographer:provided

#252 Add link to Emacs LSP client
  README.md
Labels: documentation, bot:chronographer:skip

#254 Fix vscode testing pipeline
  .github/workflows/vscode.yml
Labels: bot:chronographer:skip

#255 Make ansible syntax check fallback more resilient
  src/providers/validationProvider.ts
Labels: bot:chronographer:skip

#256 Add tests for hoverProvider
  .config/dictionary.txt
  test/fixtures/diagnostics/empty.yml
  test/fixtures/diagnostics/invalid_yaml.yml
  test/fixtures/diagnostics/lint_errors.yml
  test/fixtures/diagnostics/noHost.yml
  test/helper.ts
  test/providers/validationProvider.test.ts
Labels: enhancement, bot:chronographer:skip

#257 Simplify docs requirements
  docs/requirements.txt
Labels: bot:chronographer:skip

#258 Standardize documentation building
  .github/workflows/ci.yml
  .gitignore
  tox.ini
Labels: bot:chronographer:skip

#259 Simplify lint and docs runs on GHA
  .github/workflows/ci.yml
  package.json
  tox.ini
Labels: bot:chronographer:skip

#260 Enable test runs using tox
  tox.ini
Labels: bot:chronographer:skip

#261 Replace Number.MAX_SAFE_INTEGER with integer.MAX_VALUE
  docs/changelog-fragments.d/261.feature.md
  src/services/ansibleLint.ts
  src/services/ansiblePlaybook.ts
  src/services/validationManager.ts
  test/providers/validationProvider.test.ts
Labels: enhancement, bot:chronographer:provided

#262 Remove custom eslint/prettier single quote configuration
  .eslintrc.json
  .prettierrc.yaml
  CHANGELOG.md
  bin/ansible-language-server
  bin/version-bump-allowed
  scripts/.eslintrc.js
  scripts/check-dependencies.js
  src/ansibleLanguageService.ts
  src/interfaces/extensionSettings.ts
  src/interfaces/module.ts
  src/interfaces/pluginRouting.ts
  src/providers/completionProvider.ts
  src/providers/definitionProvider.ts
  src/providers/hoverProvider.ts
  src/providers/semanticTokenProvider.ts
  src/providers/validationProvider.ts
  src/server.ts
  src/services/ansibleConfig.ts
  src/services/ansibleLint.ts
  src/services/ansiblePlaybook.ts
  src/services/docsLibrary.ts
  src/services/executionEnvironment.ts
  src/services/metadataLibrary.ts
  src/services/settingsManager.ts
  src/services/validationManager.ts
  src/services/workspaceManager.ts
  src/utils/ansible.ts
  src/utils/commandRunner.ts
  src/utils/docsFinder.ts
  src/utils/docsFormatter.ts
  src/utils/docsParser.ts
  src/utils/execPath.ts
  src/utils/imagePuller.ts
  src/utils/misc.ts
  src/utils/yaml.ts
  test/helper.ts
  test/index.ts
  test/providers/hoverProvider.test.ts
  test/providers/validationProvider.test.ts
  test/utils/runCommand.test.ts
  test/utils/yaml.test.ts
Labels: bot:chronographer:skip

#263 Fix EE intermittent issue with auto-completion
  docs/changelog-fragments.d/263.bugfix.md
  src/services/executionEnvironment.ts
Labels: bug, bot:chronographer:provided

#265 update towncrier broken docs link
  docs/changelog-fragments.d/README.md
Labels: bot:chronographer:skip

#264 Update test to handle new ansible-lint error report
  test/providers/validationProvider.test.ts
Labels: bug, bot:chronographer:skip

#266 Configure sphinx to always use colors on output
  tox.ini
Labels: bot:chronographer:skip

#268 Enable dependabot and pinning of test dependencies
  .config/dictionary.txt
  .github/dependabot.yml
  cspell.config.yaml
  requirements.in
  requirements.txt
  tox.ini
Labels: bot:chronographer:skip

#275 Suppress console outputs and generate a clean report while testing
  .mocharc.yml
  test/consoleOutput.ts
  test/rootMochaHooks.ts
Labels: bot:chronographer:skip

#241 Upgrade globby
  package-lock.json
  package.json
  src/utils/docsFinder.ts
Labels: skip-changelog, bot:chronographer:skip

#279 Fix EE auto-completion not working issue
  docs/changelog-fragments.d/279.bugfix.md
  src/services/docsLibrary.ts
  src/services/executionEnvironment.ts
Labels: bug, bot:chronographer:provided

#276 Resolve completion of module options and sub options based on their type
  docs/changelog-fragments.d/276.feature.md
  src/providers/completionProvider.ts
  test/fixtures/completion/resolve_completion.yml
  test/providers/completionResolver.test.ts
Labels: enhancement, bot:chronographer:provided
