Repository ansible/ansible-language-server, pull requests merged in 2022-02, with the labels that each got.

#198 Integrate the release changelog preview into CD
  .github/workflows/ci.yml
  docs/changelog-fragments.d/198.misc.md
  tox.ini
Labels: enhancement, new, bot:chronographer:provided

#204 Post-process GH-facing bits of changelog draft release preview
  .github/workflows/ci.yml
  docs/changelog-fragments.d/204.misc.md
Labels: bug, enhancement, bot:chronographer:provided

#206 Fix test name for vscode-ansible extension test run
  .github/workflows/vscode.yml
Labels: bug, skip-changelog, bot:chronographer:skip

#207 Temporary disable test run on windows node
  .github/workflows/ci.yml
Labels: bug, skip-changelog, bot:chronographer:skip

#208 Add a cleanup job for removing PR/branch on fails
  .github/workflows/ci.yml
  docs/changelog-fragments.d/208.misc.md
Labels: enhancement, bot:chronographer:provided

#210 Extend release automation to link deployment page
  .github/workflows/ci.yml
  docs/changelog-fragments.d/210.misc.md
Labels: enhancement, bot:chronographer:provided

#199 Add tests for hoverProvider
  .mocharc.yml
  test/data/hover/roles.yml
  test/data/hover/tasks.yml
  test/data/hover/test_role/defaults/main.yml
  test/data/hover/test_role/meta/main.yml
  test/data/hover/test_role/tasks/main.yml
  test/data/hover/test_role/templates/motd.j2
  test/testScripts/providers/hoverTest.test.ts
  test/utils/helper.ts
Labels: enhancement, skip-changelog, bot:chronographer:skip

#213 ci: bump mocha version
  package-lock.json
  package.json
Labels: skip-changelog, bot:chronographer:skip

#214 ci: make prettier ignores consistent
  .pre-commit-config.yaml
  .prettierignore
  bin/version-bump-allowed
Labels: skip-changelog, bot:chronographer:skip

#215 ci: use prettier on markdown from repo root
  .prettierignore
  .prettierrc.yaml
  CHANGELOG.md
  README.md
Labels: skip-changelog, bot:chronographer:skip

#216 ci: use prettier on github md files
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .prettierignore
Labels: skip-changelog, bot:chronographer:skip

#220 Improve runCommand tests
  test/utils/runCommand.test.ts
Labels: bot:chronographer:skip

#224 Reformat changelog fragments with prettier
  .prettierignore
  docs/changelog-fragments.d/161.misc.md
  docs/changelog-fragments.d/164.doc.md
  docs/changelog-fragments.d/165.doc.md
  docs/changelog-fragments.d/169.misc.md
  docs/changelog-fragments.d/README.md
Labels: bot:chronographer:skip

#221 test: add pretest checks
  test/index.ts
Labels: skip-changelog, bot:chronographer:skip

#227 Separate wrapped issue/PR list @ changelog entries
  docs/changelog-fragments.d/.CHANGELOG-TEMPLATE.md.j2
Labels: bot:chronographer:skip

#217 ci: use prettier on docs md files
  .prettierignore
  docs/contributing/code_of_conduct.md
  docs/contributing/guidelines.md
  docs/contributing/security.md
  docs/development.md
Labels: skip-changelog, bot:chronographer:skip

#231 Export yaml validation function to use it in the test cases
  src/providers/validationProvider.ts
Labels: enhancement, bot:chronographer:skip

#234 Fix npm script name change in docs
  docs/development.md
Labels: bot:chronographer:skip
