Repository ansible/ansible-language-server, pull requests merged in 2022-05, with the labels that each got.

#315 chore: avoid duplicate GHA builds
  .github/workflows/ci.yml
Labels: skip-changelog, bot:chronographer:skip

#316 chore: pre-commit hooks update
  .config/dictionary.txt
  .pre-commit-config.yaml
Labels: skip-changelog, bot:chronographer:skip

#318 Add EE settings for volume mounts, container options and pull arguments
  .config/dictionary.txt
  .github/workflows/ci.yml
  .github/workflows/npm.yml
  docs/changelog-fragments.d/318.feature.md
  docs/settings.md
  package.json
  src/interfaces/extensionSettings.ts
  src/services/ansibleConfig.ts
  src/services/executionEnvironment.ts
  src/services/settingsManager.ts
  src/services/workspaceManager.ts
  src/utils/imagePuller.ts
  test/fixtures/completion/simple_tasks.yml
  test/helper.ts
  test/providers/completionProvider.test.ts
  test/providers/completionResolver.test.ts
  test/providers/hoverProvider.test.ts
  test/providers/validationProvider.test.ts
Labels: enhancement, bot:chronographer:provided

#323 Update settings-doc-generator script
  docs/changelog-fragments.d/323.bugfix.md
  docs/settings.md
  tools/settings-doc-generator.ts
Labels: bug, bot:chronographer:provided

#331 add ee service plugin path logs
  docs/changelog-fragments.d/331.misc.md
  src/services/executionEnvironment.ts
Labels: bug, bot:chronographer:provided

#334 Replace npm GHA pipeline with tox
  .config/dictionary.txt
  .github/workflows/tox.yml
  .gitignore
  tox.ini
Labels: skip-changelog, bot:chronographer:skip

#330 Fix auto-completion for modules when documentation is not displayed
  .config/dictionary.txt
  docs/changelog-fragments.d/329.bugfix.md
  src/providers/completionProvider.ts
  test/providers/completionProvider.test.ts
Labels: bug, bot:chronographer:provided

#335 Rename ci pipeline to release
  .github/workflows/release.yml
Labels: skip-changelog, bot:chronographer:skip

#336 Prepare 0.7.2 release
  .config/dictionary.txt
  .github/workflows/publish.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog, bot:chronographer:skip
