Repository ansible/ansible-language-server, pull requests merged in 2022-07, with the labels that each got.

#393 Polished test-setup.sh
  .github/workflows/task.yml
  tools/test-setup.sh
Labels: skip-changelog

#392 Add --version flag for ansible-language-server
  bin/ansible-language-server
  test/utils/runCommand.test.ts
Labels: enhancement

#395 chore: enable dependabot for actions
  .github/dependabot.yml
Labels: skip-changelog

#394 wsl: ensure o+w is not present on source code
  .config/dictionary.txt
  .github/workflows/task.yml
  Taskfile.yml
  tools/test-setup.sh
Labels: skip-changelog

#399 Bump dependencies
  .config/requirements.txt
  .pre-commit-config.yaml
  package-lock.json
  package.json
Labels: skip-changelog

#402 Release v0.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#407 Fix pr creation on release
  .github/workflows/release.yml
Labels: bug, skip-changelog

#406 Bump linkify-it-py
  .config/requirements.in
  .config/requirements.txt
Labels: skip-changelog
