Repository ansible/ansible-language-server, pull requests merged in 2023-06, with the labels that each got.

#577 Fix ansible lint config parsing
  src/services/ansibleLint.ts
  test/providers/validationProvider.test.ts
Labels: bug

#566 Update yaml to 2.x
  package-lock.json
  package.json
  src/interfaces/module.ts
  src/providers/completionProvider.ts
  src/providers/completionProviderUtils.ts
  src/providers/definitionProvider.ts
  src/providers/hoverProvider.ts
  src/providers/semanticTokenProvider.ts
  src/providers/validationProvider.ts
  src/services/docsLibrary.ts
  src/utils/docsParser.ts
  src/utils/yaml.ts
  test/fixtures/yaml/isCursorInsideJinjaBrackets.yml
  test/fixtures/yaml/isTaskParamInPlaybook.yml
  test/fixtures/yaml/isTaskParamInTaskFile.yml
  test/fixtures/yaml/isTaskParamInvalid.yml
  test/providers/validationProvider.test.ts
  test/utils/yaml.test.ts
Labels: enhancement, security

#563 Use antsibull-docs-ts to render semantic markup
  .config/dictionary.txt
  package-lock.json
  package.json
  src/utils/docsFormatter.ts
  test/providers/hoverProvider.test.ts
Labels: enhancement

#560 Return URI instead of filepath
  src/providers/definitionProvider.ts
  test/fixtures/definition/playbook_for_module_definition.yml
  test/providers/definitionProvider.test.ts
  tsconfig.json
Labels: bug
